0x0c-web

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -10,9 +10,22 @@
 
 # By: Mohammed Farahat
 
-if [ $# -lt 4 ]
-then
+
+if [ "$#" -ne 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+  exit 1
 fi
+
+PATH_TO_FILE=$1
+IP=$2
+USERNAME=$3
+PATH_TO_SSH_KEY=$4
+
+scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+if [ $? -eq 0 ]; then
+  echo "File transferred successfully."
+else
+  echo "File transfer failed."
+fi
+
